<template>
    <div>
        <h1 class="block">Icons</h1>
        <div class="flex flex-wrap gap-4">
            <template v-for="icon in icons" :key="icon">
                <div class="flex flex-col items-center gap-2">
                    <svg class="w-5 h-5">
                        <use :xlink:href="`/sprite.svg#${icon}`"></use>
                    </svg>
                    <p>{{ icon }}</p>
                </div>
            </template>
        </div>
    </div>
</template>

<script lang="ts" setup>
    // Remove duplicate entries and arrange alphabetically
    const icons = [
        'check',
        '2users',
        'new_product',
        'popular',
        'accountacny',
        'add_chart',
        'add_stock',
        'add-to-templates',
        'adjust',
        'alert',
        'archive',
        'arrow_down',
        'arrow_up',
        'ascending',
        'assign_a_manager',
        'attach',
        'back_office',
        'book-saved',
        'bookmark',
        'calendar',
        'calling',
        'chat',
        'clock',
        'close',
        'copy',
        'dashboard',
        'data-sacurity',
        'delete',
        'delivery',
        'descending',
        'details',
        'diamond',
        'discount',
        'dislike',
        'document_download',
        'dublicate',
        'edit',
        'edit2',
        'arrow-left',
        'edit',
        'emoticon',
        'expired',
        'export',
        'eye',
        'features',
        'feed',
        'feedback',
        'filter',
        'flash',
        'heart',
        'help',
        'hide',
        'menu',
        'home',
        'profile',
        'income',
        'info',
        'inventory',
        'label',
        'like',
        'link_outside',
        'location',
        'lock',
        'Logo_LE',
        'logout',
        'minus',
        'minus_circle',
        'more',
        'move_to',
        'network',
        'new',
        'notification',
        'offer',
        'pften_ordered',
        'often-orders',
        'pickup',
        'pin',
        'plus_circle',
        'plus',
        'verified',
        'connected',
        'popular_badge',
        'price tag',
        'printer',
        'profile',
        'receipt',
        'recycle',
        'refferal',
        'reply',
        'request_feedback',
        'reset',
        'save',
        'search',
        'send',
        'settings',
        'share',
        'shopping-cart',
        'snowflake',
        'star',
        'start',
        'statistics',
        'Stop',
        'template',
        'termometer',
        'translate',
        'unlock',
        'user_management',
        'user_settings',
        'watch_later',
        'wind',
        '_',
        'warn-error',
        'a_down',
        'a_left',
        'a_move',
        'clip0_2177_25235',
        'a_right',
        'logo_full',
        'logo_small',
        'bell',
        'cart2',
        'arrow2',
        'facebook3',
        'Icon-contact/social/facebook3',
        'Fill 183',
        'gdpr',
        'clip0_2807_179299',
        'instagram3',
        'Icon-contact/social/instagram3',
        'Combined Shape',
        'linkedin3',
        'Icon-contact/social/linkedin3',
        'Fill 209',
        'mastercard',
        'filter0_d_2807_179319',
        'twitter3',
        'Icon-contact/social/twitter3',
        'Fill 184',
        'youtube3',
        'Icon-contact/social/youtube3',
        'Combined Shape',
        'visa',
        'Payment Method/Visa',
        'BASE',
        'visa-logo',
        'user-profile',
        'map',
        'cub',
        'frozen',

        'boxes-pallets',
        'Icons/standart_bold',
        'package',
        'rows',
        'weight',
        'download-product',
        'add-later',
        'often-list',
        'Group 427318811',
    ]
</script>
