// constants/menuConfig.ts
import type { UserRole } from '~/types/auth'

export interface MenuItemConfig {
    key: string
    labelKey: string
    icon: string
    basePath?: string
    roles: UserRole[]
    actions?: string
    requiresAuth?: boolean
    children?: MenuItemConfig[]
    permissions?: string[]
    order?: number
    visible?: boolean
}

export interface MenuSection {
    key: string
    labelKey: string
    items: MenuItemConfig[]
    actions?: string
    roles: UserRole[]
    order: number
}

const MENU_CONFIG: MenuSection[] = [
    {
        key: 'main',
        labelKey: 'main',
        order: 1,
        roles: ['supplier', 'buyer', 'serviceProvider', 'admin'],
        items: [
            {
                key: 'dashboard',
                labelKey: 'dashboard',
                icon: 'dashboard',
                basePath: 'dashboard',
                roles: ['supplier', 'buyer', 'serviceProvider', 'admin'],
                order: 1,
            },
        ],
    },
    {
        key: 'business',
        labelKey: 'business',
        order: 2,
        roles: ['supplier', 'buyer', 'serviceProvider'],
        items: [
            {
                key: 'orders',
                labelKey: 'navigation.orders',
                icon: 'shopping-cart',
                basePath: 'orders/overview',
                roles: ['supplier', 'buyer'],
                order: 1,
                children: [
                    {
                        key: 'orders_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'orders/overview',
                        roles: ['supplier', 'buyer'],
                        order: 1,
                    },
                    {
                        key: 'orders_all',
                        labelKey: 'navigation.allOrders',
                        icon: '',
                        basePath: 'orders/all',
                        roles: ['supplier', 'buyer'],
                        order: 2,
                    },
                    {
                        key: 'orders_create',
                        labelKey: 'createOrder',
                        icon: '',
                        basePath: 'orders/create',
                        roles: ['supplier'],
                        order: 3,
                    },
                ],
            },
            {
                key: 'services',
                labelKey: 'services',
                icon: 'diamond',
                basePath: 'services',
                roles: ['serviceProvider'],
                order: 1,
                children: [
                    {
                        key: 'services_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'services',
                        roles: ['serviceProvider'],
                        order: 1,
                    },
                    {
                        key: 'services_add',
                        labelKey: 'addService',
                        icon: '',
                        basePath: 'services/new',
                        roles: ['serviceProvider'],
                        order: 2,
                    },
                    {
                        key: 'services_all',
                        labelKey: 'allServices',
                        icon: '',
                        basePath: 'services/all-services',
                        roles: ['serviceProvider'],
                        order: 3,
                    },
                ],
            },
            {
                key: 'bookings',
                labelKey: 'bookings',
                icon: 'shopping-cart',
                basePath: 'bookings/overview',
                roles: ['serviceProvider'],
                order: 2,
                children: [
                    {
                        key: 'bookings_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'bookings/overview',
                        roles: ['serviceProvider'],
                        order: 1,
                    },
                    {
                        key: 'bookings_all',
                        labelKey: 'allBookings',
                        icon: '',
                        basePath: 'bookings/all-bookings',
                        roles: ['serviceProvider'],
                        order: 2,
                    },
                ],
            },
            {
                key: 'network',
                labelKey: 'navigation.network',
                icon: 'network',
                basePath: 'network/overview',
                roles: ['supplier', 'buyer', 'serviceProvider'],
                order: 3,
                children: [
                    {
                        key: 'network_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'network/overview',
                        roles: ['supplier', 'buyer', 'serviceProvider'],
                        order: 1,
                    },
                    {
                        key: 'network_connections',
                        labelKey: 'connections',
                        icon: '',
                        basePath: 'network/connections',
                        roles: ['supplier', 'buyer', 'serviceProvider'],
                        order: 2,
                    },
                    {
                        key: 'network_followers',
                        labelKey: 'followers',
                        icon: '',
                        basePath: 'network/followers',
                        roles: ['supplier', 'buyer', 'serviceProvider'],
                        order: 3,
                    },
                    {
                        key: 'network_invitations',
                        labelKey: 'invitations',
                        icon: '',
                        basePath: 'network/invitations',
                        roles: ['supplier', 'buyer', 'serviceProvider'],
                        order: 4,
                    },
                ],
            },
        ],
    },
    {
        key: 'relationships',
        labelKey: 'relationships',
        order: 3,
        roles: ['supplier', 'buyer', 'serviceProvider'],
        items: [
            {
                key: 'buyers',
                labelKey: 'buyers',
                icon: 'user',
                basePath: 'buyers/overview',
                roles: ['supplier'],
                order: 1,
                children: [
                    {
                        key: 'buyers_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'buyers/overview',
                        roles: ['supplier'],
                        order: 1,
                    },
                    {
                        key: 'buyers_all',
                        labelKey: 'navigation.allBuyers',
                        icon: '',
                        basePath: 'buyers/all',
                        roles: ['supplier'],
                        order: 2,
                    },
                    {
                        key: 'buyers_invite',
                        labelKey: 'navigation.invitePartener',
                        icon: '',
                        actions: 'open-invite',
                        roles: ['supplier'],
                        order: 3,
                    },
                ],
            },
            {
                key: 'suppliers',
                labelKey: 'suppliers',
                icon: 'profile',
                basePath: 'suppliers/overview',
                roles: ['buyer'],
                order: 1,
                children: [
                    {
                        key: 'suppliers_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'suppliers/overview',
                        roles: ['buyer'],
                        order: 1,
                    },
                    {
                        key: 'suppliers_all',
                        labelKey: 'navigation.allSuppliers',
                        icon: '',
                        basePath: 'suppliers/all',
                        roles: ['buyer'],
                        order: 2,
                    },
                    {
                        key: 'suppliers_invite',
                        labelKey: 'navigation.invitePartener',
                        icon: '',
                        actions: 'open-invite',
                        roles: ['buyer'],
                        order: 3,
                    },
                ],
            },
            {
                key: 'clients',
                labelKey: 'clients',
                icon: 'user',
                basePath: 'clients',
                roles: ['serviceProvider'],
                order: 1,
                children: [
                    {
                        key: 'clients_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'clients',
                        roles: ['serviceProvider'],
                        order: 1,
                    },
                    {
                        key: 'clients_all',
                        labelKey: 'allClients',
                        icon: '',
                        basePath: 'clients/all-clients',
                        roles: ['serviceProvider'],
                        order: 2,
                    },
                    {
                        key: 'clients_invite',
                        labelKey: 'navigation.invitePartener',
                        icon: '',
                        actions: 'open-invite',
                        roles: ['serviceProvider'],
                        order: 3,
                    },
                ],
            },
        ],
    },
    {
        key: 'catalog',
        labelKey: 'catalog',
        order: 4,
        roles: ['supplier', 'buyer'],
        items: [
            {
                key: 'products',
                labelKey: 'products',
                icon: 'diamond',
                basePath: 'products/overview',
                roles: ['supplier', 'buyer'],
                order: 1,
                children: [
                    {
                        key: 'products_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'products/overview',
                        roles: ['supplier', 'buyer'],
                        order: 1,
                    },
                    {
                        key: 'products_add',
                        labelKey: 'addAnSku',
                        icon: '',
                        basePath: 'products/new',
                        roles: ['supplier'],
                        order: 2,
                    },
                    {
                        key: 'products_all',
                        labelKey: 'navigation.allProducts',
                        icon: '',
                        basePath: 'products/all',
                        roles: ['supplier', 'buyer'],
                        order: 3,
                    },
                    {
                        key: 'products_prices',
                        labelKey: 'prices',
                        icon: '',
                        basePath: 'products/prices',
                        roles: ['supplier'],
                        order: 4,
                    },
                    {
                        key: 'products_features',
                        labelKey: 'features',
                        icon: '',
                        basePath: 'products/features',
                        roles: ['supplier'],
                        order: 5,
                    },
                ],
            },
            {
                key: 'sales',
                labelKey: 'sales',
                icon: 'sales',
                basePath: 'sales',
                roles: ['supplier'],
                order: 2,
            },
            {
                key: 'inventory',
                labelKey: 'inventory',
                icon: 'inventory',
                basePath: 'inventory',
                roles: ['supplier'],
                order: 3,
            },
        ],
    },
    {
        key: 'communication',
        labelKey: 'communication',
        order: 5,
        roles: ['supplier', 'buyer', 'serviceProvider'],
        items: [
            {
                key: 'documents',
                labelKey: 'navigation.documents',
                icon: 'receipt',
                basePath: 'documents/all',
                roles: ['supplier', 'buyer', 'serviceProvider'],
                order: 1,
                children: [
                    {
                        key: 'documents_all',
                        labelKey: 'navigation.allDocuments',
                        icon: '',
                        basePath: 'documents/all',
                        roles: ['supplier', 'buyer', 'serviceProvider'],
                        order: 1,
                    },
                    {
                        key: 'documents_add',
                        labelKey: 'navigation.createDocument',
                        icon: '',
                        basePath: 'documents/create',
                        roles: ['supplier', 'serviceProvider'],
                        order: 2,
                    },
                ],
            },
            {
                key: 'messenger',
                labelKey: 'chat',
                icon: 'messenger',
                basePath: 'chat',
                roles: ['supplier', 'buyer', 'serviceProvider'],
                order: 2,
            },
        ],
    },
    {
        key: 'admin',
        labelKey: 'administration',
        order: 6,
        roles: ['admin'],
        items: [
            {
                key: 'alerts',
                labelKey: 'alerts',
                icon: 'alert',
                basePath: 'alerts',
                roles: ['admin'],
                order: 1,
                children: [
                    {
                        key: 'alerts_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'alerts',
                        roles: ['admin'],
                        order: 1,
                    },
                    {
                        key: 'alerts_history',
                        labelKey: 'alertHistory',
                        icon: '',
                        basePath: 'alerts/history',
                        roles: ['admin'],
                        order: 2,
                    },
                ],
            },
            {
                key: 'moderation',
                labelKey: 'moderation',
                icon: 'pen',
                basePath: 'moderation',
                roles: ['admin'],
                order: 2,
                children: [
                    {
                        key: 'moderation_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'moderation',
                        roles: ['admin'],
                        order: 1,
                    },
                    {
                        key: 'moderation_users',
                        labelKey: 'users',
                        icon: '',
                        basePath: 'moderation/users',
                        roles: ['admin'],
                        order: 2,
                    },
                    {
                        key: 'moderation_products',
                        labelKey: 'products',
                        icon: '',
                        basePath: 'moderation/products',
                        roles: ['admin'],
                        order: 3,
                    },
                    {
                        key: 'moderation_posts',
                        labelKey: 'posts',
                        icon: '',
                        basePath: 'moderation/posts',
                        roles: ['admin'],
                        order: 4,
                    },
                ],
            },
            {
                key: 'statistics',
                labelKey: 'statisticsAndKPI',
                icon: 'statistics',
                basePath: 'statistics',
                roles: ['admin'],
                order: 3,
                children: [
                    {
                        key: 'statistics_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'statistics',
                        roles: ['admin'],
                        order: 1,
                    },
                    {
                        key: 'statistics_financial',
                        labelKey: 'financial',
                        icon: '',
                        basePath: 'statistics/financial',
                        roles: ['admin'],
                        order: 2,
                    },
                    {
                        key: 'statistics_users',
                        labelKey: 'users',
                        icon: '',
                        basePath: 'statistics/users',
                        roles: ['admin'],
                        order: 3,
                    },
                    {
                        key: 'statistics_orders',
                        labelKey: 'orders',
                        icon: '',
                        basePath: 'statistics/orders',
                        roles: ['admin'],
                        order: 4,
                    },
                    {
                        key: 'statistics_products',
                        labelKey: 'products',
                        icon: '',
                        basePath: 'statistics/products',
                        roles: ['admin'],
                        order: 5,
                    },
                ],
            },
            {
                key: 'management',
                labelKey: 'userManagement',
                icon: 'user-management',
                basePath: 'management',
                roles: ['admin'],
                order: 4,
                children: [
                    {
                        key: 'management_overview',
                        labelKey: 'overview',
                        icon: '',
                        basePath: 'management',
                        roles: ['admin'],
                        order: 1,
                    },
                    {
                        key: 'management_admins',
                        labelKey: 'admins',
                        icon: '',
                        basePath: 'management/admins',
                        roles: ['admin'],
                        order: 2,
                    },
                    {
                        key: 'management_sales',
                        labelKey: 'salesTeam',
                        icon: '',
                        basePath: 'management/sales',
                        roles: ['admin'],
                        order: 3,
                    },
                ],
            },
        ],
    },
    {
        key: 'settings',
        labelKey: 'settings',
        order: 100,
        roles: ['supplier', 'buyer', 'serviceProvider', 'admin'],
        items: [
            {
                key: 'settings',
                labelKey: 'settings',
                icon: 'settings',
                basePath: 'settings',
                roles: ['supplier', 'buyer', 'serviceProvider', 'admin'],
                order: 1,
            },
            {
                key: 'support',
                labelKey: 'support',
                icon: 'help-circle',
                basePath: 'support',
                roles: ['supplier', 'buyer', 'serviceProvider', 'admin'],
                order: 2,
            },
            {
                key: 'guide',
                labelKey: 'guide',
                icon: 'book-saved',
                basePath: 'guide',
                roles: ['supplier', 'buyer', 'serviceProvider', 'admin'],
                order: 3,
            },
        ],
    },
]

export { MENU_CONFIG }
